#! /bin/bash

# Written by Ankit R Gadiya

# Scripts suppported
lock="lock"
githelper="githelper"
tasks="tasks"
diary="diary"
help="--help"
YEAR=`date +"%Y"`

# Installation script
if [ $# = 0 ]
    then
        echo "Try again with command line arguments"
        echo "For help use --help"
elif [ $# != 0 ]
    then
        if [[ "$1" == "$lock"  ||  "$1" == "$githelper" ]]
        then
            mkdir $HOME/.scripts
            cp $1 $HOME/.scripts
            echo "export PATH=$PATH:$HOME/.scripts/" >> $HOME/.bashrc
            echo "Set directories"
            sleep 2s
            nano ~/.scripts/$1
            echo "Done!"
            echo "Restart shell!"
        elif [ "$1" == "$tasks" ]
        then
            mkdir $HOME/Lists
            touch $HOME/Lists/tasks.md
            mkdir $HOME/.scripts
            cp $1 $HOME/.scripts
            echo "export PATH=$PATH:$HOME/.scripts/" >> $HOME/.bashrc
            echo "Populate the tasks"
            echo "Done"
            echo "Restart shell!"
        elif [ "$1" == "$diary" ]
        then
            cd $HOME
            wget https://github.com/ankitrgadiya/simple-jekyll/archive/master.zip
            unzip master.zip -d Diary
            cd Diary
            sed -i -e 's/blog/diary/g' _config.yml
            sed -i -e 's/Blog/diary/g' _config.yml
            git init
            git checkout -b $YEAR
            git add .
            git commit -m "Diary Initiated"
            mkdir $HOME/.scripts
            cp $1 $HOME/.scripts
            echo "export PATH=$PATH:$HOME/.scripts/" >> $HOME/.bashrc
            echo "Done"
            echo "Restart shell!"

        elif [ "$1" == "$help" ]
        then
            echo "╦┌┐┌┌─┐┌┬┐┌─┐┬  ┬  "
            echo "║│││└─┐ │ ├─┤│  │  "
            echo "╩┘└┘└─┘ ┴ ┴ ┴┴─┘┴─┘"
            echo "Usage: install <option>"
            echo "Scripts which can be installed:"
            echo "* lock"
            echo "* githelper"
            echo "* tasks"
            echo "* diary"
        else
            echo "Try again with command line arguments"
            echo "For help use --help"
            echo "Failed"
        fi
fi
