#! /bin/bash

# Location Variables
scr="/tmp/lockbg.png"
logo="$HOME/Pictures/Logo/Logo-small.png"
final="/tmp/lockfinal.png"

# Script
scrot "$scr"
convert "$scr" -blur 0x5 $f "$scr"
convert -gravity center -composite "$scr" "$logo" "$final"
i3lock -u -i "$final"
rm "$final" "$scr"
