#! /bin/bash

# Written by Ankit R Gadiya
# Written during Google Code-in 2016

# Command Line Arguments
CURRENT="current"
NEXT="next"
UPDATE="update"
HELP="help"
SHOW="show"

# Script
if [ $# = 0 ]
    then
        cat ~/Lists/tasks.md
fi
if [ "$1" == "$CURRENT" ]
    then
        tail -n 6 ~/Lists/tasks.md | head -n 2
fi
if [ "$1" == "$NEXT" ]
    then
        tail -n 3 ~/Lists/tasks.md
fi
if [ "$1" == "$UPDATE" ]
    then
        nano ~/Lists/tasks.md
fi
if [ "$1" == "$HELP" ]
    then
        echo "┌┬┐┌─┐┌─┐┬┌─┌─┐"
        echo " │ ├─┤└─┐├┴┐└─┐"
        echo " ┴ ┴ ┴└─┘┴ ┴└─┘"
        echo "Help chart for tasks script"
        echo "* current  - Current Tasks"
        echo "* next     - next tasks"
        echo "* help     - Lists all options"
        echo "* update   - Opens tasks.md in nano"
fi
echo "Happy Coding :-)"
