#! /bin/bash

# Connecting to internet
echo "Starting..."
sudo dhclient eth0
if [ $? -eq 0 ]; then
    echo OK
else
    echo FAIL
fi

# Installing network manager and wifi capabilities
echo "Installing network capabilities..."
sudo apt-get install network-manager wireless-tools firmware-atheros
if [ $? -eq 0 ]; then
    echo OK
else
    echo FAIL
fi
sudo sed -i -e 's/false/true/g' /etc/NetworkManager/NetworkManager.conf
if [ $? -eq 0 ]; then
    echo OK
else
    echo FAIL
fi
sudo service network-manager restart
if [ $? -eq 0 ]; then
    echo OK
    echo "Done!"
else
    echo FAIL
fi

# Installing predefined most used softwares
echo "Installing utilites..."
sudo apt-get install i3-wm i3lock i3status gedit vim tmux moc firefox-esr lxappearance xfce4-terminal gnome-themes-standard openssh-server git feh gstreamer0.10-fluendo p7zip unzip
if [ $? -eq 0 ]; then
    echo OK
    echo "Done!"
else
    echo FAIL
fi

# Setting up ssh server
echo "Setting up SSH server..."
sudo update-rc.d -f ssh remove
sudo update-rc.d -f ssh defaults
sudo update-rc.d -f ssh enable 2 3 4 5
sudo service ssh restart
if [ $? -eq 0 ]; then
    echo OK
else
    echo FAIL
fi
echo "Done!"

# Setting up my dotfiles
echo "Setting up dotfiles..."
git clone https://github.com/ankitrgadiya/dotfiles
cp -r dotfiles/.i3 ~/.
cp -r dotfiles/.mutt ~/.
cp dotfiles/.muttrc ~/
vim ~/.mutt/account.com.gmail.ankit4922
vim ~/.mutt/account.com.pawnmail.me
rm -rf dotfiles
echo "Done!"

# Git configuration
echo "Git config"
echo -n "Git username: "
read GITNAME
git config --global user.name "$GITNAME"
echo -n "Git email: "
read GITMAIL
git config --global user.email "$GITMAIL"

while true
do
  echo "Do you wanna setup Github aliases"
  echo -n "'yes' or 'no': "
  read REPLY
  case $REPLY in
    'yes')
      alias=1
      break;;
    'no')
      alias=0
      break;;
    *)
      echo "Wrong input try again";;
  esac
done
if [ "$alias" == 1 ]
  then
    echo -n "Github username: "
    read USERNAME
    echo -n "Alias: "
    read ALIAS
    git config --global url.https://github.com/$USERNAME/.insteadof $ALIAS:
    git config --global url.https://github.com/.insteadof gh:
    echo "Github = gh:"
    echo "Github username = $ALIAS:"
    echo "Done!"
else
  echo "Alias setup cancelled"
fi


echo "Reboot now!"
