#! /bin/bash

# Connecting to internet
echo "Starting..."
sudo dhclient eth0
if [ $? -eq 0 ]; then
    echo OK
else
    echo FAIL
fi

# Installing network manager and wifi capabilities
echo "Installing network capabilities..."
sudo apt-get install network-manager wireless-tools firmware-atheros
if [ $? -eq 0 ]; then
    echo OK
else
    echo FAIL
fi
sudo sed -i -e 's/false/true/g' /etc/NetworkManager/NetworkManager.conf
if [ $? -eq 0 ]; then
    echo OK
else
    echo FAIL
fi
sudo service network-manager restart
if [ $? -eq 0 ]; then
    echo OK
    echo "Done!"
else
    echo FAIL
fi

# Installing predefined most used softwares
echo "Installing utilites..."
sudo apt-get install vim tmux openssh-server git p7zip unzip
if [ $? -eq 0 ]; then
    echo OK
    echo "Done!"
else
    echo FAIL
fi

# Setting up ssh server
echo "Setting up SSH server..."
sudo update-rc.d -f ssh remove
sudo update-rc.d -f ssh defaults
sudo update-rc.d -f ssh enable 2 3 4 5
sudo service ssh restart
if [ $? -eq 0 ]; then
    echo OK
else
    echo FAIL
fi
echo "Done!"

# Setting up my dotfiles
echo "Setting up dotfiles..."
git clone https://github.com/ankitrgadiya/dotfiles
cp dotfiles/.gitconfig ~/.
cp dotfiles/.tmux.conf ~/.
cp dotflies/.vimrc ~/.
cp -r dotfiles/.mutt ~/.
cp dotfiles/.muttrc ~/.
echo "Change passwords"
sleep 3s
vim .mutt/account.com.egurjan.arg
vim .mutt/account.com.ankitrga.me
vim .mutt/account.com.ankitrgadiyain.me
vim .mutt/account.com.gmail.ankit4922
rm -rf dotfiles
echo "Done!"
